FROM domjudge/judgehost:latest

 
ENV DAEMON_ID=0 \
    CONTAINER_TIMEZONE=Asia/Shanghai \
    JUDGEDAEMON_PASSWORD=judgehost123 \
    DOMSERVER_BASEURL=http://localhost/

 # docker run -itd --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro  --hostname judgedaemon-0 

  
