apiVersion: v1
kind: Service
metadata:
  name: domserver-svc
spec:
  selector:
    app: domserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 80
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 360000

