apiVersion: apps/v1            
kind: StatefulSet             
metadata:               
  name: judgehost       
  labels:               
    app: judgehost      
spec:                   
  replicas: 1
  selector:             
    matchLabels:        
      app: judgehost    
  serviceName: "judgehost-svc"
  template:             
    metadata:           
      labels:           
        app: judgehost  
    spec:               
      containers:       
      - name: judgehost 
        image: domjudge/judgehost:8.1.3     
        env:
        - name: DAEMON_ID
          value: "0"
        - name: CONTAINER_TIMEZONE
          value: Asia/Shanghai
        - name: JUDGEDAEMON_PASSWORD
          value: judgehost123
        - name: DOMSERVER_BASEURL
          value: http://1.13.157.50/
        securityContext:
          privileged: true
        volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - judgehost   
                      - domserver
              topologyKey: kubernetes.io/hostname

      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
 
 
