FROM domjudge/domserver:latest

ENV MYSQL_HOST=sh-cynosdbmysql-grp-0vwgms1m.sql.tencentcdb.com \
    MYSQL_PORT=21113 \
    MYSQL_USER=domserver \
    MYSQL_DATABASE=domjudge \
    MYSQL_PASSWORD=DOMServer123 \
    MYSQL_ROOT_PASSWORD=DOMServer123 \
    CONTAINER_TIMEZONE=Asia/Shanghai 


EXPOSE 80
